name: Test Practice
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Print success message
        run: echo "Tests passed!"
