name: Test Practice
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: development-key-${{hashFiles('**/package-lock.json')}}
      - name: Get Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Print success message
        run: echo "Tests passed!"
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      buildoutput: ${{ steps.build-step.outputs.buildoutput }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: development-key-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: build job output
        id: build-step
        run: echo "buildoutput=success" >> "$GITHUB_OUTPUT"
      - name: Upload articats
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
      - name: Print success message
        run: echo "Build succeeded!"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Articats
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output files
        run: ls
      - name: Build output
        run: echo ${{needs.build.outputs.buildoutput}}
      - name: Output message
        run: echo "Deployment succeeded!"
