name: Test Practice
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Print success message
        run: echo "Tests passed!"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Print success message
        run: echo "Build succeeded!"
